### ISSUE TITLE
events output in chat after leaving event arena

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#166] opened 2021-06-16 21:52 UTC
Reported by **DoA|^#a81236Backflip** (16/06/2021 23:52:56)
  
  **Description:**
  events output in chat after leaving event arena

  **Reproduction:**
  participate in an event, leave arena before event finished

**Comment by zjkdev** [comment] 2021-07-01 21:15
Duplicate of Lumiverse/Atlas-Issues#189

**Closed as completed by zjkdev** 2021-07-01 21:15 UTC
Labels: Bug, Medium Priority
