### ISSUE TITLE
going through shades

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#111] opened 2021-04-02 09:56 UTC
Reported by **.#JoeL** (02/04/2021 09:56:37)
  
  **Description:**
  i pass trough some object( and makes me fail)wich are important for completing the map, they are supposed to have collision

  **Reproduction:**
  playing for long time i thing triggers it for no reason

**Comment by qualiti** [comment] 2021-04-05 19:38
duplicate of #110

**Closed as completed by qualiti** 2021-04-05 19:38 UTC
Labels: Bug, Low Priority
