### ISSUE TITLE
sorting maps by Liked on the dashboard sometimes gets stuck

### ISSUE THREAD

**Issue by brianmta** [Lumiverse/Atlas-Issues#126] opened 2021-04-22 12:37 UTC
woshin reported that even though he changed sort by Liked maps back to All maps, he was only able to see his liked maps on the userpanel. reconnect likely solves it

**Comment by qualiti** [comment] 2021-04-22 21:56
duplicate of #92

**Closed as completed by qualiti** 2021-04-22 21:56 UTC
Labels: Bug, Medium Priority
