### ISSUE TITLE
deleting a map from the FUN arenas through dashboard doesnt work

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#80] opened 2021-02-26 12:32 UTC
Reported by **#ff7c50lv*#0f775abrian** (26/02/2021 12:32:36)
  
  **Description:**
  if you delete a map via dashboard from FDD or CATCH the map will stay in the arena even though you get the successful notification. it only works via /deletemap command

  **Reproduction:**
  delete a map from FDD or Catch

**Comment by tsprotte** [comment] 2021-02-26 12:59
Duplicate of #1

**Closed by tsprotte** 2021-02-26 12:59 UTC
Labels: Bug, Low Priority
