### ISSUE TITLE
numberplate text not set when spawning in something other than an Infernus

### ISSUE THREAD

**Issue by dnl-k** [Lumiverse/Atlas-Issues#199] opened 2021-07-10 14:39 UTC
**Describe the bug**
The numberplate text is not set when spawning with a different vehicle

**To Reproduce**
1. Spawn with a vehicle that's not an infernus (e.g. on Race To Death III)

**Comment by zjkdev** [comment] 2021-07-11 15:14
Closing this as it is not a bug.

**Closed as completed by zjkdev** 2021-07-11 15:14 UTC
Labels: Bug, Low Priority
