### ISSUE TITLE
Teleport stuck

### ISSUE THREAD

**Issue by iamlumiverse** [Lumiverse/Atlas-Issues#5] opened 2021-02-12 19:46 UTC
Reported by **sy#6BADACn.R#E3E3E3hae** (24/01/2021 15:36:15)
  
  **Description:**
  Teleport stuck

  **Reproduction:**
  Teleport stuck

**Comment by pkfln** [comment] 2021-03-15 18:58
Clarification: Sometimes you get stuck when you hit a teleport marker. I heard from some players, that this often happens when you keep pressing the acceleration-key while teleporting.

**Comment by brianmta** [comment] 2021-05-19 17:16
duplicate of https://github.com/Lumiverse/Atlas-Issues/issues/119

**Closed by brianmta** 2021-05-19 17:16 UTC
Labels: Bug, Medium Priority
