### ISSUE TITLE
Training: Player being able to spectate other spectator

### ISSUE THREAD

**Issue by pzrwk** [Lumiverse/Atlas-Issues#181] opened 2021-06-24 21:37 UTC
**Describe the bug**
When trying to spectate other spectator you see blue marker and as many peds as spectators count

**To Reproduce**
Spectate a player who's also a spectator

**Screenshots**
![mta-screen_2021-06-24_23-32-37](https://user-images.githubusercontent.com/79587134/123335641-0e0b1880-d545-11eb-848b-cf7e7ea9cf52.png)

**Comment by qualiti** [comment] 2021-10-19 15:54
duplicate of #95

**Closed as completed by qualiti** 2021-10-19 15:54 UTC
Labels: Bug, Medium Priority
